name: Addition App Deployment

on:
  push:
  #workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Test application
        run: python -m py_compile app.py #Commonly used in a pipeline to check whether a Python file has syntax errors.

      - name: Build
        run: echo "Build successful"

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.py"
          target: "/home/ubuntu/addition-app"

      - name: Run application on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |   # With '|' we can write multiple commands, multiple lines of text..... Script is input parameter that tells ssh action that these r the cmds want to execute on remote EC2 machine.
            cd /home/ubuntu/addition-app
            python3 app.py
